### ISSUE TITLE
Support limited access scenarios

### ISSUE THREAD

**Issue by justingkao** [IvanJosipovic/KubeUI#568]
I import the config yaml and can successfully connect the cluster.
But all resources are empty (plus: I only have the limited access to the specified namespace)
![image](https://github.com/IvanJosipovic/KubeUI/assets/10344954/e05af8b1-0cca-4224-98fe-b9d0122a8592)

**Comment by justingkao** [comment]
Background: I don't have the access to run `Kubectl  get namespace`

**Comment by IvanJosipovic** [comment]
Fixed as of https://github.com/IvanJosipovic/KubeUI/releases/tag/v1.0.0-alpha.72
